### ISSUE TITLE
More columns in CSV than needed

### ISSUE THREAD

**Issue by MichalRafalski** [j256/simplecsv#2]
Hello,
I have an issue that my CSV file has more columns than fields in the object.
I get an error "[column name 'X' is unknown, type no valid header lin]"

Is it possible to ignore extra columns and just put required data into the object?

I tried:
`            Collection<ParseError> parseErrors = new ArrayList<ParseError>();
            List<myObject> = processor.readAll(file, parseErrors);`
and
`            List<myObject> = processor.readAll(file, null);`

I found documentation an example: https://256stuff.com/sources/simplecsv/
to use 
`List readAccounts =
   csvProcessor.readAll(csvFile, true /* read in header */, true /* validate header */, null);`
but I don't see method readAll with 4 attributes.

Thanks,
MR

**Comment by j256** [comment]
I think you want to set `processor.setAllowPartialLines(true)`.  See: https://256stuff.com/sources/simplecsv/javadoc/simplecsv/com/j256/simplecsv/processor/CsvProcessor.html#setAllowPartialLines-boolean-
