### ISSUE TITLE
Order exported CSV columns

### ISSUE THREAD

**Issue by oliexdev** [j256/simplecsv#3]
First of all awesome library. I tried out quite a lot of CSV libraries but most of them didn't work because of some gradle build dex error. Yours are really simple to use and up to date. That was the CSV library that I was looking for. :1st_place_medal: 

I have one question is it possible to sort the exported CSV columns? Currently they are sorted by the column names but is it also possible that I can order independently from the column names? For example to set the first column to a specific date field?

**Comment by j256** [comment]
Thanks for the feedback.  Are you talking about the order of the columns as they appear in the CSV output?  Right now they are sorted not by name but by their location in the Java entity.

If you want to change the order of the fields to be something else you can just reorder them in the Java entity or you can use the [afterColumn CsvField setting](https://256stuff.com/sources/simplecsv/javadoc/simplecsv/com/j256/simplecsv/common/CsvColumn.html#afterColumn--).

Hope this helps.

**Comment by oliexdev** [comment]
I cannot confirm that the columns are sorted by their location in the Java entity.

I have the following class which is looking like:

```
public class Measurement {
    private int userId;
    private boolean enabled;
    @CsvColumn (format = "dd.MM.yyyy HH:mm")
    private Date dateTime;
    @CsvColumn
    private float weight;
    @CsvColumn
    private float fat;
    @CsvColumn
    private float water;
    @CsvColumn
    private float muscle;
    @CsvColumn
    private float lbw;
    @CsvColumn
    private float waist;
    @CsvColumn
    private float hip;
    @CsvColumn
    private float bone;
    @CsvColumn
    private String comment;

   //....
}
```

if I export it with:

```
CsvProcessor<ScaleMeasurement> csvProcessor = new CsvProcessor<ScaleMeasurement>(ScaleMeasurement.class);
File csvFile = new File(filename);
csvProcessor.writeAll(csvFile, scaleMeasurementList, true);
```

I will get the following CSV file

```
"bone","comment","dateTime","fat","hip","lbw","muscle","waist","water","weight"
0.0,"","08.01.2018 19:19",0.0,0.0,0.0,0.0,0.0,0.0,90.0
0.0,"","04.01.2018 19:19",0.0,0.0,0.0,0.0,0.0,0.0,80.0
```

which is ordered by the column name. 
But the afterColumn setting works. Thank you.

Is there a special field name for afterColumn to bring a column to the front? Like for example `@CsvColumn (afterColumn = none)`? Or do I have to set all other fields to bring a certain field to the front?

**Comment by Moseqi** [comment]
Try ordering variable name like
int a
int b
...
and so on

**Comment by j256** [comment]
Sorry for the late response @oliexdev.  For the record, just leaving the `afterColumn` unspecified on the first column will work.  I'm sure you figured that out by now.
